### ISSUE TITLE
[discussion] remove this repo and move all nginx configuration to configmaps in budgetkey-k8s

### ISSUE THREAD

**Issue by OriHoch** [OpenBudget/open-budget-nginx-frontend#6]
because nginx is tightly coupled to the infrastructure, I find it easier to keep it as part of the infra.

also, it's useful to run it as root template - giving it access to all values of subcharts (otherwise each chart only sees it's own values)

this allows to configure nginx based on configuration of subcharts - which makes sense because they are tightly coupled (for example service names are used as the proxy_pass in nginx server rules)

for example - 
https://github.com/Midburn/midburn-k8s/blob/master/templates/nginx-conf.yaml

**Comment by akariv** [comment]
I don't mind doing this - there's no special functionality here anyway.
